-- Why this file exists:
-- It is a reproducible schema + policy reference for new environments and teammates.
-- If your Supabase tables and RLS policies are already created, you can keep this file
-- for documentation/versioning and usually do not need to run it again.
--
-- Run this in Supabase SQL editor if you need to create the prototype schema.
-- Tables: rooms (registry), schedule (permission list), attendance_log (sign-in sheet).

create table if not exists public.rooms (
  id int8 generated by default as identity primary key,
  room_name text not null,
  beacon_uuid text not null unique
);

create table if not exists public.schedule (
  id int8 generated by default as identity primary key,
  student_email text not null,
  room_beacon_id text not null,
  start_time time not null,
  end_time time not null
);

alter table public.schedule
  add column if not exists end_time time;

update public.schedule
set end_time = (start_time + interval '55 minutes')::time
where end_time is null;

alter table public.schedule
  alter column end_time set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'schedule_end_time_after_start_chk'
  ) then
    alter table public.schedule
      add constraint schedule_end_time_after_start_chk
      check (end_time > start_time);
  end if;
end
$$;

create index if not exists schedule_lookup_idx
  on public.schedule (student_email, room_beacon_id, start_time, end_time);

create table if not exists public.attendance_log (
  id int8 generated by default as identity primary key,
  student_email text not null,
  room_name text not null,
  status text not null default 'Present',
  created_at timestamptz not null default now()
);

create index if not exists attendance_log_lookup_idx
  on public.attendance_log (student_email, created_at desc);

alter table public.rooms enable row level security;
alter table public.schedule enable row level security;
alter table public.attendance_log enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'rooms'
      and policyname = 'allow_select_rooms_from_anon'
  ) then
    create policy allow_select_rooms_from_anon
      on public.rooms
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'schedule'
      and policyname = 'allow_select_schedule_from_anon'
  ) then
    create policy allow_select_schedule_from_anon
      on public.schedule
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'attendance_log'
      and policyname = 'allow_insert_attendance_from_anon'
  ) then
    create policy allow_insert_attendance_from_anon
      on public.attendance_log
      for insert
      to anon
      with check (true);
  end if;
end
$$;

-- Optional sample data for quick testing.
insert into public.rooms (room_name, beacon_uuid)
values ('Room 101', '0000181c-0000-1000-8000-00805f9b34fb')
on conflict (beacon_uuid) do nothing;

insert into public.schedule (student_email, room_beacon_id, start_time, end_time)
values
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '08:17:00', '09:13:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '09:15:00', '10:08:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '10:10:00', '11:03:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '11:05:00', '11:35:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '11:40:00', '12:10:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '12:12:00', '13:05:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '13:07:00', '14:00:00'),
  ('student@school.edu', '0000181c-0000-1000-8000-00805f9b34fb', '14:02:00', '14:55:00');
